name: molpal

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.8
  - python=3.11
  - pytorch=2.6.0
  - pip
  - pip:
    - configargparse
    - h5py
    - numpy
    - ray==2.44.1
    - ray[tune]==2.44.1
    - rdkit
    - pytorch-lightning
    - scikit-learn
    - tensorflow
    - tensorflow-addons
    - tqdm
